# MIT License
# Copyright 2024 Mikael Forsberg (github.com/mkforsb)

auto_classes = {"GtkToggleButton": ["text-button", "toggle"]}

element_names = {
    "GtkAdjustment": None,
    "GtkBox": "box",
    "GtkButton": "button",
    "GtkCheckButton": "checkbutton",
    "GtkDrawingArea": "widget",
    "GtkDropDown": "dropdown",
    "GtkEntry": "entry",
    "GtkEntryBuffer": None,
    "GtkFlowBox": "flowbox",
    "GtkFlowBoxChild": "flowboxchild",
    "GtkFrame": "frame",
    "GtkGrid": "grid",
    "GtkHeaderBar": "headerbar",
    "GtkLabel": "label",
    "GtkListBox": "list",
    "GtkListBoxRow": "row",
    "GtkListView": "listview",
    "GtkMenuButton": "menubutton",
    "GtkNotebook": "notebook",
    "GtkOverlay": "overlay",
    "GtkPaned": "paned",
    "GtkProgressBar": "progressbar",
    "GtkScrolledWindow": "scrolledwindow",
    "GtkSpinButton": "spinbutton",
    "GtkStack": "stack",
    "GtkStackPage": None,
    "GtkStackSwitcher": "stackswitcher",
    "GtkStringList": None,
    "GtkWindow": "window",
}

cssable_props = [
    "content-height",
    "content-width",
    "halign",
    "hexpand",
    "icon-name",
    "margin-bottom",
    "margin-end",
    "margin-start",
    "margin-top",
    "position",
    "show-separators",
    "show-text",
    "valign",
    "vexpand",
    "visible",
    "wide-handle",
    "width-request",
    "height-request",
    "xalign",
    "yalign",
]
